$schema: "https://json-schema.org/draft/2020-12/schema"
description: "Schema for user-provided configuration files."
type: object
additionalProperties: false
properties:
  temporal_scope:
    type: object
    description: "The temporal scope of the simulation."
    properties:
      start:
        type: string
        format: date-time
        description: "Start date and time of the simulation in ISO 8601 format."
      end:
        type: string
        format: date-time
        description: "End date and time of the simulation in ISO 8601 format."
    required:
      - start
      - end
  spatial_scope:
    type: object
    description: "The spatial scope of the simulation."
    properties:
      minx:
        type: number
        description: "Minimum longitude of the spatial scope."
      maxx:
        type: number
        description: "Maximum longitude of the spatial scope."
      miny:
        type: number
        description: "Minimum latitude of the spatial scope."
      maxy:
        type: number
        description: "Maximum latitude of the spatial scope."
    required:
      - minx
      - maxx
      - miny
      - maxy
  use_load:
    type: string
    description: "The source of load data to use in the simulation. Options are 'entsoe_api' or 'entsoe_opsd'."
    enum:
      - "load_entsoe_api"
      - "load_entsoe_opsd"
