# Module settings that users cannot modify.
resources:
  automatic:
    # Links for automatically downloaded files
    load_entsoe_opsd: "https://data.open-power-system-data.org/time_series/2019-06-05/time_series_60min_stacked.csv"
    population: "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/GHS_POP_GLOBE_R2023A/GHS_POP_E2020_GLOBE_R2023A_54009_1000/V1-0/GHS_POP_E2020_GLOBE_R2023A_54009_1000_V1_0.zip"
    population_tif: "GHS_POP_E2020_GLOBE_R2023A_54009_1000_V1_0.tif"

load_entsoe_api:
  countries:
    # Download all ENTSO-E countries
    - "ALB"
    - "AUT"
    - "BIH"
    - "BEL"
    - "BGR"
    - "CHE"
    - "CYP"
    - "CZE"
    - "DEU"
    - "DNK"
    - "EST"
    - "ESP"
    - "FIN"
    - "FRA"
    - "GBR"
    - "GRC"
    - "HRV"
    - "HUN"
    - "IRL"
    - "ITA"
    - "LTU"
    - "LUX"
    - "LVA"
    - "MNE"
    - "MKD"
    - "NLD"
    - "NOR"
    - "POL"
    - "PRT"
    - "ROU"
    - "SRB"
    - "SWE"
    - "SVN"
    - "SVK"
    - "TUR"

population:
  # Bounding box to clip population raster to ENTSO-E area
  bounds: [-13., 34., 37., 72.]
  crs: "EPSG:4326"
  buffer: 0
