# Module settings that users cannot modify.
resources:
  automatic:
    # Links for automatically downloaded files
    load_entsoe_opsd: "https://data.open-power-system-data.org/time_series/2019-06-05/time_series_60min_stacked.csv"
    population: "https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/GHSL/GHS_POP_GLOBE_R2023A/GHS_POP_E2020_GLOBE_R2023A_54009_1000/V1-0/GHS_POP_E2020_GLOBE_R2023A_54009_1000_V1_0.zip"

load_entsoe_api:
  start: "2015-01-01T00:00Z"
  end: "2020-12-31T23:00Z"

population:
  # Bounding box to clip population raster to ENTSO-E area
  minx: -13.
  miny: 34.
  maxx: 37.
  maxy: 72.
